export { Header } from "../components/Header";
export { Footer } from "../components/Footer";
export { ScrollToTopBtn } from "../components/ScrollToTopBtn";
export { Landing } from "./Landing";
export { About } from "./About";
export { FAQ } from "./FAQ";
export { ErrorPage } from "./ErrorPage";
export { CurrentYear } from "./Enroll/CurrentYear";
export { Other as EnrollOther } from "./Enroll/Other";
export { Other } from "./Other";
export { Grade } from "./Search/Grade";
export { Extra } from "./Search/Extra";
export { SignUp } from "./SignUp";
export { Recent } from "./Recent";
export { Training } from "./Training";
