export { Header, Footer, ScrollToTopBtn, Blog } from "../components";
export { ErrorPage } from "./ErrorPage";
export { Landing } from "./Landing";
export { Grade10, TradeSchool, Other } from "./Enroll";
export { Grade, Extra } from "./Search";
export { Ref } from "./Ref";
export { SignUp } from "./SignUp";
export { Recent } from "./Recent";
export { Training } from "./Training";
export { FAQ } from "./FAQ";
export { Privacy } from "./Privacy";
export { Statement } from "./Statement";
